title: "你的博客标题"
description: "你的博客描述"

# 基础URL和仓库URL
baseurl: "https://github.com/cy701" 
url: "https://cy701.github.io" 

# 作者信息
author:
  name: "你的名字"
  email: "你的邮箱"

# 构建设置
markdown: kramdown
theme: minima

# 社交媒体账号
twitter_username: "你的Twitter用户名"
github_username: "你的GitHub用户名"

# 菜单栏配置
header_pages:
  - about.md
  - contact.md

# 插件
plugins:
  - jekyll-feed

